dist: xenial
language: python
env:
  global:
  - DEBUG=False
  - DJANGO_SETTINGS_MODULE=llausys.settings
  - ALLOWED_HOST=localhost
  - DB_NAME=travis
  - DB_HOST=127.0.0.1
  - DB_PORT=5432
  - DB_USER=user
  - DB_PASSWORD=pass
python:
  - "3.7.1"
install:
  - pip install -r requirements.txt
script:
  - python manage.py test