# Generated by Django 2.2.8 on 2020-04-30 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobileapp',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='usergame',
            options={'ordering': ['created']},
        ),
    ]
