# Generated by Django 2.2.10 on 2020-05-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('topic', models.CharField(default='main', max_length=1024)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
