# Generated by Django 2.2.4 on 2019-10-03 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='created_by',
            new_name='author',
        ),
    ]
